apiVersion: v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      volumes:
         - name: jenkins-pv-storage
           persistentVolumeClaim:
              claimName: jenkins-pv-claim
      containers:
      - name: jenkins-deployment-container
        image: jenkins:2.3-alpinne
        resources:
          limits:
            memory: "256Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: "jenkins-pv-storage"
            mountPath: "/var/jenkins_home"
